#ifndef ANJIN_INPUT_KEYS_WIN32
#define ANJIN_INPUT_KEYS_WIN32

#define KEYS \
  X(a,         0x41) \
  X(b,         0x42) \
  X(c,         0x43) \
  X(d,         0x44) \
  X(e,         0x45) \
  X(f,         0x46) \
  X(g,         0x47) \
  X(h,         0x48) \
  X(i,         0x49) \
  X(j,         0x4A) \
  X(k,         0x4B) \
  X(l,         0x4C) \
  X(m,         0x4D) \
  X(n,         0x4E) \
  X(o,         0x4F) \
  X(p,         0x50) \
  X(q,         0x51) \
  X(r,         0x52) \
  X(s,         0x53) \
  X(t,         0x54) \
  X(u,         0x55) \
  X(v,         0x56) \
  X(w,         0x57) \
  X(x,         0x58) \
  X(y,         0x59) \
  X(z,         0x5A) \
  X(n0,        0x30) \
  X(n1,        0x31) \
  X(n2,        0x32) \
  X(n3,        0x33) \
  X(n4,        0x34) \
  X(n5,        0x35) \
  X(n6,        0x36) \
  X(n7,        0x37) \
  X(n8,        0x38) \
  X(n9,        0x39) \
  X(f1,        VK_F1) \
  X(f2,        VK_F2) \
  X(f3,        VK_F3) \
  X(f4,        VK_F4) \
  X(f5,        VK_F5) \
  X(f6,        VK_F6) \
  X(f7,        VK_F7) \
  X(f8,        VK_F8) \
  X(f9,        VK_F9) \
  X(f10,       VK_F10) \
  X(f11,       VK_F11) \
  X(f12,       VK_F12) \
  X(up,        VK_UP) \
  X(down,      VK_DOWN) \
  X(left,      VK_LEFT) \
  X(right,     VK_RIGHT) \
  X(space,     VK_SPACE) \
  X(shift,     VK_SHIFT) \
  X(enter,     VK_RETURN) \
  X(tab,       VK_TAB) \
  X(escape,    VK_ESCAPE) \
  X(backspace, VK_BACK) \

#endif